# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'snake.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 665)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(860, 640))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.painterWidget = QtWidgets.QWidget(self.centralwidget)
        self.painterWidget.setMinimumSize(QtCore.QSize(640, 640))
        self.painterWidget.setObjectName("painterWidget")
        self.horizontalLayout.addWidget(self.painterWidget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scoreLcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.scoreLcd.setMinimumSize(QtCore.QSize(0, 48))
        self.scoreLcd.setObjectName("scoreLcd")
        self.verticalLayout.addWidget(self.scoreLcd)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.firstPlayer = QtWidgets.QLabel(self.centralwidget)
        self.firstPlayer.setText("")
        self.firstPlayer.setObjectName("firstPlayer")
        self.gridLayout.addWidget(self.firstPlayer, 0, 1, 1, 1)
        self.oneLabel = QtWidgets.QLabel(self.centralwidget)
        self.oneLabel.setObjectName("oneLabel")
        self.gridLayout.addWidget(self.oneLabel, 0, 0, 1, 1)
        self.fifthPlayer = QtWidgets.QLabel(self.centralwidget)
        self.fifthPlayer.setText("")
        self.fifthPlayer.setObjectName("fifthPlayer")
        self.gridLayout.addWidget(self.fifthPlayer, 4, 1, 1, 1)
        self.secondPlayer = QtWidgets.QLabel(self.centralwidget)
        self.secondPlayer.setText("")
        self.secondPlayer.setObjectName("secondPlayer")
        self.gridLayout.addWidget(self.secondPlayer, 1, 1, 1, 1)
        self.fiveLabel = QtWidgets.QLabel(self.centralwidget)
        self.fiveLabel.setObjectName("fiveLabel")
        self.gridLayout.addWidget(self.fiveLabel, 4, 0, 1, 1)
        self.thirdPlayer = QtWidgets.QLabel(self.centralwidget)
        self.thirdPlayer.setText("")
        self.thirdPlayer.setObjectName("thirdPlayer")
        self.gridLayout.addWidget(self.thirdPlayer, 2, 1, 1, 1)
        self.threeLabel = QtWidgets.QLabel(self.centralwidget)
        self.threeLabel.setObjectName("threeLabel")
        self.gridLayout.addWidget(self.threeLabel, 2, 0, 1, 1)
        self.twoLabel = QtWidgets.QLabel(self.centralwidget)
        self.twoLabel.setObjectName("twoLabel")
        self.gridLayout.addWidget(self.twoLabel, 1, 0, 1, 1)
        self.fourLabel = QtWidgets.QLabel(self.centralwidget)
        self.fourLabel.setObjectName("fourLabel")
        self.gridLayout.addWidget(self.fourLabel, 3, 0, 1, 1)
        self.fourthPlayer = QtWidgets.QLabel(self.centralwidget)
        self.fourthPlayer.setText("")
        self.fourthPlayer.setObjectName("fourthPlayer")
        self.gridLayout.addWidget(self.fourthPlayer, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout.addWidget(self.resetButton)
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout.addWidget(self.exitButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Score board"))
        self.oneLabel.setText(_translate("MainWindow", "1."))
        self.fiveLabel.setText(_translate("MainWindow", "5."))
        self.threeLabel.setText(_translate("MainWindow", "3."))
        self.twoLabel.setText(_translate("MainWindow", "2."))
        self.fourLabel.setText(_translate("MainWindow", "4."))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))